name: "sit-portal-server"

services:
  redis:
    image: redis:8.2.1-alpine
    container_name: sit-portal-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --save 60 1000
    volumes:
      - sit-portal-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - sit-portal-network
    mem_limit: 256m
    memswap_limit: 256m

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
      target: runtime
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: sit-portal-api
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./logs:/server/logs
      - api-tmp:/tmp
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/shared/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sit-portal-network
    mem_limit: 512m
    memswap_limit: 512m
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
      target: runtime
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: sit-portal-celery
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/server/logs
      - celery-tmp:/tmp
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "supervisorctl", "-c", "/etc/supervisor/conf.d/supervisord.conf", "status", "celery-worker", "celery-beat"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 90s
    networks:
      - sit-portal-network
    mem_limit: 1.25g
    memswap_limit: 1.25g
    security_opt:
      - no-new-privileges:true

volumes:
  sit-portal-redis-data:
    driver: local
  api-tmp:
    driver: local
  celery-tmp:
    driver: local

networks:
  sit-portal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16